# Generated by Django 2.1.5 on 2019-03-09 14:24

from django.conf import settings
from django.db import migrations, models
import exel_handler_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datafile', models.FileField(upload_to=exel_handler_app.models.user_directory_path)),
                ('owner', models.ForeignKey(on_delete=models.SET(exel_handler_app.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
