# Generated by Django 2.1.5 on 2019-03-09 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import exel_handler_app.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exel_handler_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField()),
                ('date', models.DateField(blank=True)),
                ('course', models.IntegerField()),
                ('lectures', models.IntegerField(blank=True)),
                ('practise_less', models.IntegerField(blank=True)),
                ('lab_works', models.IntegerField(blank=True)),
                ('modular_control', models.IntegerField(blank=True)),
                ('term_consultation', models.IntegerField(blank=True)),
                ('exam_consultation', models.IntegerField(blank=True)),
                ('credit', models.IntegerField(blank=True)),
                ('exam', models.IntegerField(blank=True)),
                ('course_work', models.IntegerField(blank=True)),
                ('vkr_bac', models.IntegerField(blank=True)),
                ('vkr_spec', models.IntegerField(blank=True)),
                ('vkr_mag', models.IntegerField(blank=True)),
                ('practise_ruk', models.IntegerField(blank=True)),
                ('gos_exam', models.IntegerField(blank=True)),
                ('rez_vkr', models.IntegerField(blank=True)),
                ('zach_vkr', models.IntegerField(blank=True)),
                ('asp_ruk', models.IntegerField(blank=True)),
                ('other', models.IntegerField(blank=True)),
                ('all', models.IntegerField()),
                ('added_by', models.ForeignKey(on_delete=models.SET(exel_handler_app.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearningBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('B', 'Budget'), ('C', 'Contract')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='datatable',
            name='base',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='exel_handler_app.LearningBase'),
        ),
        migrations.AddField(
            model_name='datatable',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exel_handler_app.Group'),
        ),
        migrations.AddField(
            model_name='datatable',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exel_handler_app.Subject'),
        ),
    ]
