# Generated by Django 2.1.5 on 2019-03-09 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exel_handler_app', '0002_auto_20190309_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatable',
            name='asp_ruk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exel_handler_app.LearningBase'),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='course_work',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='credit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='exam',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='exam_consultation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='gos_exam',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='lab_works',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='lectures',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='modular_control',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='other',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='practise_less',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='practise_ruk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='rez_vkr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='term_consultation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='vkr_bac',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='vkr_mag',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='vkr_spec',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='zach_vkr',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
