# Generated by Django 2.1.5 on 2019-03-09 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exel_handler_app', '0003_auto_20190309_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatable',
            name='course',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exel_handler_app.Group'),
        ),
    ]
